### PR TITLE
Upgrade to Gradle 7.3.1

### LINKED ISSUE #1117: Use the latest version of Gradle in gradle projects
Currently v6.4.1 is being used while generating gradle projects. Latest as of this writing is 6.6

I'll raise a PR for the same 😄

### LINKED ISSUE #1286: Upgrade to Gradle 7.3.1
Gradle 7.3.1 has just been released

### PR DESCRIPTION
**Pull request by rbleuse**
Fixes #1286

### CODE REVIEW

**Comment by snicoll** [comment]
@rbleuse thanks for the PR. Have you checked that the wrapper script and jar files haven't been updated in this version?

**Comment by rbleuse** [comment]
Yes both haven't been updated 👍

**Comment by snicoll** [comment]
@rbleuse thank you for the follow-up and for making your first contribution to Spring Initializr.

**Comment by snicoll** [comment]
Superseded by #1299

**Pull request closed without merging**
