### PR TITLE
Update to Gradle 2.10

### PR DESCRIPTION
**Pull request by praseodym**
Including update to Gradle Wrapper. Through .gitattributes we force
gradlew.bat to have CRLF line endings (as expected on Windows).

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks, have you signed the CLA?

**Comment by praseodym** [comment]
Yes, I just did.

**Comment by snicoll** [comment]
Thanks for the PR, I've upgraded to 2.12 in https://github.com/spring-io/initializr/commit/9aee15ce6a52b5bcdf184166193502950d269eb4

**Comment by praseodym** [comment]
Cheers!

**Pull request closed without merging**
