### PR TITLE
Upgrade to Kotlin 1.2.50

### PR DESCRIPTION
**Pull request by kevcodez**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kevcodez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=681)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=681) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kevcodez Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=681)!

**Comment by snicoll** [comment]
Thanks for the PR but we can do single line versions ourselves. What you're probably asking is for users to be able to use Kotlin 1.2.50. 

Spring Framework master hasn't been upgraded yet. The process is to first do that, then migrate Spring Boot and then we can decide what to do here. 

Ping @sdeleuze

**Comment by sdeleuze** [comment]
Given previous regressions in 1.2.x0 releases, I prefer to wait 1.2.51 before upgrading.

**Comment by snicoll** [comment]
Thanks @sdeleuze.

@kevcodez thanks for the PR, we will upgrade start.spring.io in due course when Spring Framework and Spring Boot have upgraded.

**Comment by kevcodez** [comment]
Thanks for the clarification, I was not aware.

**Pull request closed without merging**
