### PR TITLE
Adds link to github page for dependency in UI.

### PR DESCRIPTION
**Pull request by jonnynabors**
Adds fontawesome to resources.

screen shot 2018-02-23 at 2 52 03 pm

This is what a configuration for a dependency would look like to add this to the page.
```
links:
  - rel: github
     href: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-starters/spring-boot-starter-web
     description: Building a RESTful Web Service
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jonnynabors Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=607)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=607) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jonnynabors Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=607)!

**Comment by snicoll** [comment]
Thanks for the PR @jonnynabors  - We meant to investigate another route for links from the Web UI, see #371

Paging @bclozel for additional feedback.

**Comment by jonnynabors** [comment]
I've rebased this on top of the changes from the Spring Boot 2 update.

**Comment by snicoll** [comment]
Thanks a lot @jonnynabors but we've decided not to add links to the UI itself as we've indicated in #353

**Pull request closed without merging**
