### PR TITLE
InitializrMetadataV2JsonMapper hardocdes type attribute for TypeCapability

### PR DESCRIPTION
**Pull request by Veneckiy**
Using type from capability.getType().getName() for field 'type'

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Veneckiy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=1186)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=1186) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Veneckiy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=1186)!

**Comment by snicoll** [comment]
@Veneckiy good catch, looks like an oversight on our end when the type abstraction was introduced.

**Comment by snicoll** [comment]
@Veneckiy Thank you for making your first contribution to Spring Initializr

**Pull request closed without merging**
