### PR TITLE
Add spring-batch-test when Spring Batch is selected

### PR DESCRIPTION
**Pull request by TimRiemer**
add SpringBatchTestRequestPostProcessor and SpringBatchTestRequestPostProcessorTests for gh-491

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@TimRiemer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=516) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@TimRiemer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=516)!

**Comment by snicoll** [comment]
@TimRiemer thank you so much for your first contribution to Spring Initializr. This is now merged.

**Comment by TimRiemer** [comment]
@snicoll Sorry, thought I singned the CLA already. Thank you for the merge and the opportunity!

**Pull request closed without merging**
