### PR TITLE
Update to Gradle 2.9

### PR DESCRIPTION
**Pull request by danhyun**
[Review on Reviewable](https://reviewable.io/reviews/spring-io/initializr/160)

### CODE REVIEW

**Comment by snicoll** [comment]
@wilkinsona WDYT?

**Comment by wilkinsona** [comment]
2.9 has just been released so, if we're going to upgrade, it'd make more sense to jump to 2.9 imo.

**Comment by danhyun** [comment]
It was! I'll update pr

**Comment by danhyun** [comment]
Updated to latest Gradle

**Comment by snicoll** [comment]
Have you signed the CLA btw?

**Comment by wilkinsona** [comment]
The dependency management plugin builds happily against 2.9

**Comment by danhyun** [comment]
I've just signed the ICLA

**Pull request closed without merging**
