### PR TITLE
gmavenplus

### PR DESCRIPTION
**Pull request by sjyun**
add gmavenplus configuration in pom.xml
gmavenplus1.4 / invokeDynamic false

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the PR. 

We want that the groovy-based projects that the service generates use gmavenplus as well. And we need to handle issues such as cross-compilation since the current solution does support it. That being said, a good way to experiment that would be to move our own build to it. 

Have you signed the CLA? (link in CONTRIBUTING)

**Comment by sjyun** [comment]
yes i signed  and agree to spring initializr Contribution License Agreement

**Comment by snicoll** [comment]
Thanks for the PR but this required a bit more thinking. I have updated Spring Initializr's build to groovy in https://github.com/spring-io/initializr/commit/cc85d3f0034ca75b356901fbd9455f29aab2b31e and generated projects in https://github.com/spring-io/initializr/commit/05565dee3fbcacd4aa9ff61ae10f85a684744268

**Comment by sjyun** [comment]
thanks a lot for your kind information

happy new year~!


2015-12-30 0:15 GMT+09:00 Stéphane Nicoll <notifications@github.com>:

> Thanks for the PR but this required a bit more thinking. I have updated
> Spring Initializr's build to groovy in cc85d3f
> <https://github.com/spring-io/initializr/commit/cc85d3f0034ca75b356901fbd9455f29aab2b31e>
> and generated projects in 05565de
> <https://github.com/spring-io/initializr/commit/05565dee3fbcacd4aa9ff61ae10f85a684744268>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-io/initializr/pull/92#issuecomment-167808283>.
>



-- 
======================================================================
Warm Regards,
grayjin
https://keybase.io/grayjin <https://keybase.io/pniederw>
https://www.facebook.com/thecodinglive
http://www.slideshare.net/SukjinYun1
https://github.com/sjyun
======================================================================

**Pull request closed without merging**
