### PR TITLE
add scala language support

### PR DESCRIPTION
**Pull request by fkowal**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@fkowal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=673)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=673) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fkowal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=673)!

**Comment by snicoll** [comment]
@fkowal thank you very much for your first contribution to Spring Initializr. Unfortunately, we have decided not to support Scala, see [this issue](https://github.com/spring-io/initializr/issues/393#issuecomment-357106468) for more details.

**Comment by fkowal** [comment]
Can’t help to think. That politics has everything to do with this.

**Pull request closed without merging**
