### PR TITLE
Tweak gitignores in generated project

### PR DESCRIPTION
**Pull request by dsyer**
Two changes:

1. don't use leading "/" on directory names. That way when the project becomes multi module, or a module in a larger project, the directories get excluded recursively.

2. add an additional sts4 artifact (probably linux only).

### CODE REVIEW

**Comment by wilkinsona** [comment]
This could do with being separate pull requests so that each change can be easily accepted or rejected individually.

I think the change that removes the leading `/` from directories should be rejected as it will regress https://github.com/spring-io/initializr/issues/623.

**Comment by dsyer** [comment]
Fair enough about #623 (for people that have packages called "build"). There must be a better way for multi-module projects to exclude gradle build artifacts. People do this all the time?

**Comment by wilkinsona** [comment]
This might work (for Java. We'd need variants for Groovy and Kotlin):

```
build/
!**/src/main/java/**
!**/src/test/java/**
```

With the following files and directory structure:

```
.
├── build
│   └── content.txt
├── project1
│   ├── build
│   │   └── content.txt
│   └── src
│       ├── main
│       │   └── java
│       │       └── com
│       │           └── example
│       │               └── build
│       │                   └── content.txt
│       └── test
│           └── java
│               └── com
│                   └── example
│                       └── build
│                           └── content.txt
└── src
    ├── main
    │   └── java
    │       └── com
    │           └── example
    │               └── build
    │                   └── content.txt
    └── test
        └── java
            └── com
                └── example
                    └── build
                        └── content.txt
```

Git sees the following files:

```
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   .gitignore
	new file:   project1/src/main/java/com/example/build/content.txt
	new file:   project1/src/test/java/com/example/build/content.txt
	new file:   src/main/java/com/example/build/content.txt
	new file:   src/test/java/com/example/build/content.txt
```

**Comment by dsyer** [comment]
I would expect `src/main` and `src/test` to be all non-ignorable (irrespective of the source language). Maybe that would simplifiy it.

**Comment by wilkinsona** [comment]
Nice. That should work. I don't think it should be specific to Gradle builds, though. Maven builds will have the same problem with `target/` and a package named `target`.

**Comment by dsyer** [comment]
True, that. I consider a java package called "target" in a maven build to be pathological. But if we want to be completely confident not to break anyone I get the point.

**Comment by wilkinsona** [comment]
> I consider a java package called "target" in a maven build to be pathological

Even if they work for Target? /cc @danveloper (although I suspect he'd be using Gradle anyway).

**Comment by wilkinsona** [comment]
Superseded by #927.

**Pull request closed without merging**
