### PR TITLE
upgrade azure spring to 0.2.3

### PR DESCRIPTION
**Pull request by sophiaso**
@yungez @Matthew-Dong @yaweiw

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sophiaso Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=588)!

**Comment by yungez** [comment]
@snicoll

**Comment by snicoll** [comment]
I had a look to the changes since 0.2.2 and I've raised a number of issues.

**Comment by sophiaso** [comment]
@snicoll Two PRs are created for the issues you created [PR1](https://github.com/Microsoft/azure-spring-boot/pull/260) and [PR2](https://github.com/Microsoft/azure-spring-boot/pull/263).

**Comment by sophiaso** [comment]
Renamed branch and a new PR is created #596

**Pull request closed without merging**
