### PR TITLE
Add Orika starter

### PR DESCRIPTION
**Pull request by rakk**
Adding orika strarter option.

Read more about the starter:
https://github.com/akihyro/orika-spring-boot-starter

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rakk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=687)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=687) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rakk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=687)!

**Comment by wilkinsona** [comment]
Thanks for the pull request. The starter doesn't look as it if it's really in active development any more. We'd like to see Spring Boot 2.0 support and a commitment to the ongoing maintenance of the starter before we'd consider adding it to start.spring.io. I'll leave this open for a while to see if the necessary changes are commitments are made.

**Comment by snicoll** [comment]
We've decided not to support that use case (see https://github.com/spring-io/initializr/pull/715#issuecomment-422445457). Thanks for the PR anyway.

**Pull request closed without merging**
