### PR TITLE
added KIE projects (jBPM, drools, optaplanner) spring boot starters

### PR DESCRIPTION
**Pull request by mswiderski**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mswiderski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=582)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=582) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mswiderski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=582)!

**Comment by snicoll** [comment]
@mswiderski thanks for the proposal. Please review [the guidelines for 3rd party starters](https://github.com/spring-io/initializr/wiki/Guidelines-for-3rd-Party-Starters) and update your PR accordingly.

**Comment by mswiderski** [comment]
@snicoll thanks for the link, I looked through it and I believe it's all covered. I actually built it based on the official docs. Could you please let me know what is missing?

**Comment by snicoll** [comment]
@mswiderski the most obvious one that comes to mind is 
> start.spring.io will host one starter POM per 3rd party library

We won't accept 4 entries for this so please chose one that represent the top level use case and we can then discuss based on that. Thanks

**Comment by mswiderski** [comment]
even if those are three different OSS projects? jBPM Drools and OptaPlanner?

**Comment by mswiderski** [comment]
anyway, updated PR so it includes just one. Later one we could add (if possible) others. thanks

**Comment by mswiderski** [comment]
@snicoll anything I can do here or is it under review? 7.6.0 of KIE Server is now released and available in maven central

**Comment by snicoll** [comment]
@mswiderski Sorry. We've reviewed that entry and I am afraid we are not keen to add it. Initializr holds reusable, composable components. This starter has too many well-defined opinions (i.e. actuator + jersey) to be one of them.

**Pull request closed without merging**
