### PR TITLE
Omit the package directory structure for Kotlin projects

### PR DESCRIPTION
**Pull request by JanGroot**
as per [this recommendation](https://kotlinlang.org/docs/coding-conventions.html#directory-structure) in the Kotlin documentation

Fixes gh-1403

### CODE REVIEW

**Comment by JanGroot** [comment]
Ah, I missed a test. 
I'll have a look.

**Comment by JanGroot** [comment]
Hmm that will require some extra work. I

**Comment by JanGroot** [comment]
See commit message, probably needs a little help for a more elegant solution on the unittest.

**Comment by JanGroot** [comment]
If this is added, some guides like https://github.com/spring-guides/tut-spring-boot-kotlin will need minor updates to reflect this change.

**Comment by sdeleuze** [comment]
Thanks for this contribution.

This guideline targets "pure Kotlin projects" but also specifies
> On JVM: In projects where Kotlin is used together with Java, Kotlin source files should reside in the same source root as the Java source files, and follow the same directory structure: each file should be stored in the directory corresponding to each package statement.

While there will be likely more projects not having both Java and Kotlin sources, some projects will require it, so generating a project structure incompatible with this use case, which is a strength of Kotlin especially in the context of Spring, looks not necessarily something desirable to me.

> If this is added, some guides like https://github.com/spring-guides/tut-spring-boot-kotlin will need minor updates to reflect this change.

I think there are other places like documentation where some code sample specify the package and various other places we would have to update. This would be a pretty wide scope of changes.

A third important realization is that we may want to keep consistency in term of project structure between Java, Groovy and Kotlin.

For those reasons, I think I would recommend to reject this PR even if I understand the reason for submitting it.

**Comment by snicoll** [comment]
Thanks Sébastien for the guidance and @JanGroot for the suggestion.

**Pull request closed without merging**
