### PR TITLE
Add support for Maven profile

### PR DESCRIPTION
**Pull request by xjs191919**
add profile to pom.xml

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@xjs191919 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=1026)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=spring-io/initializr&pullRequestId=1026) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@xjs191919 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=spring-io/initializr&pullRequestId=1026)!

**Comment by snicoll** [comment]
It's been a while @xjs191919. We are wondering if you'd like to review the comments in this PR?

**Comment by xjs191919** [comment]
i am very sorry ,i think it is beyond the range of my ability

**Pull request closed without merging**
