### PR TITLE
Upgrade to mybatis 1.2.1 and 1.3.0

### PR DESCRIPTION
**Pull request by eddumelendez**
artifacts will be released in the next days and will be available via maven central.

### CODE REVIEW

**Comment by snicoll** [comment]
@eddumelendez next time, could you please submit the PR only once the artifacts are available? Thanks!

**Comment by eddumelendez** [comment]
@snicoll sure, I will. Sorry for any inconvenience

**Comment by kazuki43zoo** [comment]
@eddumelendez  ( @snicoll )

If 1.4.x.SNAPSHOT version is selected, initializr does not output version tag. (I've tried 1.4.6.BUILD-SNAPSHOT)

```xml
<dependency>
	<groupId>org.mybatis.spring.boot</groupId>
	<artifactId>mybatis-spring-boot-starter</artifactId>
</dependency>
```

Result per versions are as follows:

| spring-boot version | mybatis-spring-boot-starter version | Result |
| ---------------------- | ----------------------------------------- | ------- |
| 2.0.0.BUILD-SNAPSHOT | 1.3.0 | OK |
| 1.5.3.BUILD-SNAPSHOT | 1.3.0 | OK |
| 1.5.2.RELEASE | 1.3.0 | OK |
| **1.4.6.BUILD-SNAPSHOT** | **no version** | **NG** |
| 1.4.5.RELEASE | 1.2.1 | OK |
| 1.3.8.RELEASE | 1.1.1 | OK |

**Comment by kazuki43zoo** [comment]
@snicoll 

I have a question.
Since 1.2.1 and 1.3.0, we added the `mybatis-spring-boot-starter-test` (new artifact for testing support including `@MybatisTest`). Could "Spring Initializr" output two artifacts(`mybatis-spring-boot-starter` and `mybatis-spring-boot-starter-test`) together if select a `MyBatis` tag ?

**Comment by snicoll** [comment]
@kazuki43zoo the version range is wrong, I'll fix it. For your other question the answer is no, see #152 - I am not a huge fan of having several dependencies of something without a bom anyway.

**Comment by kazuki43zoo** [comment]
@snicoll Thanks for fix !!

**Comment by kazuki43zoo** [comment]
>  For your other question the answer is no, see #152 - I am not a huge fan of having several dependencies of something without a bom anyway.

@snicoll Thanks for answer !! I will refer it.

**Pull request closed without merging**
