### PR TITLE
Default platform version is not translated to backward compatible format

### PR DESCRIPTION
**Pull request by ggerbaud**
See #1112

### CODE REVIEW

**Comment by snicoll** [comment]
Thanks for the report and the PR. I had some trouble to understand what you were reporting as the versions were a little bit confusing. Rephrasing below for reference.

Assuming a simple metadata config:

```
initializr:
  boot-versions:
    - name: Latest SNAPSHOT
      id: 2.4.2-SNAPSHOT
      default: false
    - name: 2.4.1
      id: 2.4.1
      default: true
```

The output when requested with `v2.1` is as follows:

```
"bootVersion": {
        "default": "2.4.1",
        "type": "single-select",
        "values": [
            {
                "id": "2.4.2.BUILD-SNAPSHOT",
                "name": "Latest SNAPSHOT"
            },
            {
                "id": "2.4.1.RELEASE",
                "name": "2.4.1"
            }
        ]
```

The switch of format is applied for individual identifiers, however the default reference to an existing platform version is not harmonised.

**Comment by snicoll** [comment]
We've decided to switch to `0.9.1-SNAPSHOT` and have a release sooner than expected to include this fix.

**Comment by snicoll** [comment]
@ggerbaud thank you for making your first contribution to Spring Initializr. A `0.9.1-SNAPSHOT` should be available shortly, if you have time to text the fix against your use case and report back, that would be very much appreciated. Thanks again.

**Comment by ggerbaud** [comment]
I tested 0.9.1-SNAPSHOT against my use case and it's ok
Thanks for the merge

**Pull request closed without merging**
