### PR TITLE
Add optional url property to a dependency

### PR DESCRIPTION
**Pull request by dsyer**
If present the "tag" name and checkbox description are rendered as
a link to the URL. So it could be a link to a guide, for instance.
To test the new feature I just added one url to the "web"
dependency.

### CODE REVIEW

**Comment by snicoll** [comment]
Interesting, thanks. This is my take on this one https://github.com/spring-io/initializr/issues/163#issuecomment-163266175

Initializr is client-agnostic so we should define how other clients can use that information.

**Comment by dsyer** [comment]
Yeah, I agree with the comments you made on #163 (it's hard to organize the information if there is more than one link per dependency). But if it's at most one, or if one is special, then this PR feels like a useful starting point.

**Comment by joshlong** [comment]
all clients can use HTML. Or, even better as long we constrain the type of data to null or just a link, they can avoid using it if they don't want to.

**Comment by dsyer** [comment]
Latest commit turns url (singular) into links (plural with ids and descriptions).

**Comment by snicoll** [comment]
@bclozel I'd like to merge this PR but I don't like how links are currently displayed in the web ui. Do you have some suggestions about it?

An additional ping to @@olivergierke for the metadata side of things.

**Comment by olivergierke** [comment]
The only comment I have is that on the client side of things you should stick to the media type's way of representing links. In the JSON we currently expose it's HAL's way. One could move to the more commonly used `href` instead of `url`. `id` probably has to be defined in some way but it feels more like a `rel` to me, although `rel`s don't necessarily have to be unique but we could of course make that sure ourselves here.

**Comment by olivergierke** [comment]
Oh, and if there's no need to identify a "primary" one, why not just list them in an unordered list with a "Related" header?

**Comment by snicoll** [comment]
There is a need to identify a primary one. I'd assume that if a client can only show one link, it needs to know which one to take. @olivergierke isn't there something in Spring Hateoas that helps with that? We're already using it.

**Comment by snicoll** [comment]
ping @bclozel :-)

**Comment by snicoll** [comment]
OK so we have a PR for the UI side of things. I'd like to rework this PR to generate something like this

```json
{
  "description": "Full-stack web development with Tomcat and Spring MVC",
  "id": "web",
  "name": "Web",
  "_links": {
    "guide": {
      "href": "https://spring.io/guides/gs/rest-service/",
      "title": "Building a RESTful Web Service"
    },
    "chapter": {
      "href": "http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc"
    }
  }
}
```

The nature of the link is free but it would be nice to support a few, that gives the opportunity to clients to chose an appropriate icon for it.

**Comment by spring-operator** [comment]
+1 this is awesome @snicoll

**Comment by snicoll** [comment]
For further reference here are the issue for IDE support:

* STS: https://issuetracker.springsource.com/browse/STS-4427
* Netbeans: https://github.com/AlexFalappa/nb-springboot/issues/71
* IntelliJ IDEA has already an implementation that will be available in the upcoming 2017.1 EAP

**Pull request closed without merging**
