### PR TITLE
Add support for AxonFramework

### PR DESCRIPTION
**Pull request by abuijze**
A number of people inside Pivotal asked me to submit a pull request to add AxonFramework to the Spring intializr. So, here it is.

None of the categories felt like a perfect match, and I didn't want to stress things by suggesting a new category. I added it to the I/O category, as it felt closest to the libraries mentioned there.

Feel free to comment or ask for changes.

### CODE REVIEW

**Comment by snicoll** [comment]
@abuijze sorry for the late reply. A short ping to acknowledge we've seen this one and are reviewing it.

**Comment by abuijze** [comment]
Hi @snicoll, did you get to review the PR? Let me know if there is anything you'd like to me to change.

**Comment by snicoll** [comment]
Hi @abuijze, apologizes for the delay. I've flagged this one for team attention so that we have one more round on it. This should hopefully happen this week still. 

Thank you!

**Comment by snicoll** [comment]
@abuijze thanks for the PR but we prefer to keep third party contributions limited for the moment. I've added a reference to Axon Framework on our [3rd parties starters list](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/README.adoc). We can use that as an incubation period and reconsider later.

Thanks!

**Pull request closed without merging**
