### PR TITLE
Fix gradle template

### PR DESCRIPTION
**Pull request by nobusue**
- change module 'groovy' to 'groovy-all'
- update gradle wrapper version to 2.2.1

### CODE REVIEW

**Comment by dsyer** [comment]
Neither of these changes is a great idea I'm afraid. The "groovy-all" jar pulls in dependencies that you might not want (like "groovy-templates" for instance). And we compile and build the Boot plugin against Gradle 1.x so unless you know for sure that it will work with 2.x we need to be cautious.

**Comment by nobusue** [comment]
I agree with Gradle version. 
For groovy dependency, I have a different opinion. I think these type of templates are helpful not only for experts but beginners. To assist beginners, it should provide "fail-safe" default. Module "groovy" doesn't have important packages like "groovy.json" package, so it is shortcoming. (Groovy experts can understand and modify dependencies, I think.)

**Comment by dsyer** [comment]
I definitely see your point there. But Spring Boot makes certain assumptions according to what is in the classpath, so it's much better that the user specifically choose what is there. I guess it's a learning curve.

**Comment by nobusue** [comment]
Thanks, @dsyer.  Now I've caught Spring Boot's philosophy and I respect it.
Hopefully, it would be nice to enhance Spring Initializr having "Groovy module selection" feature. (I may try if I have spare time..)

**Pull request closed without merging**
