### PR TITLE
revert version of Zipkin UI so that it works with the any recent version of Spring Cloud

### PR DESCRIPTION
**Pull request by joshlong**
revert version of Zipkin UI so that it works with the any recent version of Spring Cloud

### CODE REVIEW

**Comment by snicoll** [comment]
What does that mean? It needs at least a range, right? We can't offer that dep for m a version that do not support it.

**Comment by spring-operator** [comment]
it works on Boot 1.3 / Spring Cloud RC1

**Comment by snicoll** [comment]
_only_? _as from_ ?

**Comment by spring-operator** [comment]
Wait, let's try this again. I'm after a result. I want to go to
start.spring.io and search for Zipkin UI. I *don't* want to have to select
Spring Boot 1.3.4 SNAPSHOTS. What do i need to do to get that result?

**Comment by snicoll** [comment]
I am after result and consistency. `Zipkin UI` should only show up for the boot versions that work with it. I don't know that library so please answer that question and we can take it from there. Am I right to assume this is available only as from `Brixton.RC1` (in particular _not_ `Angel`).

**Comment by spring-operator** [comment]
it *could* work with anything. it's just a webjar, basically. But, yes,
you'd want it with Brixton.RC1 or better.

**Comment by snicoll** [comment]
`Brixton.RC1` is `1.3.3.RELEASE` so we should use that instead.

**Pull request closed without merging**
