### PR TITLE
Use spaces in the starter-build.gradle template consistently.

### PR DESCRIPTION
**Pull request by FrontierPsychiatrist**
The template adds tabs for some dependencies and spaces for others which generates an inconsisten build.gradle. I've replaces the tabs with 4 spaces since most lines had spaces.

Since the version is still SNAPSHOT I didn't increase it, hope that's ok this way?

### CODE REVIEW

**Comment by snicoll** [comment]
Cool thanks!

**Comment by FrontierPsychiatrist** [comment]
Ok, do you want me to do that? I'd be happy to help.

I usually prefer spaces, the Spring style guideline requires tabs: [guideline](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Code-Style).

**Comment by snicoll** [comment]
Cool, that would be very nice indeed. I'll merge some fixes today (that unfortunately include what you've done in this PR already). I'll ping you through a close of this PR and then you can go ahead if you want to apply that to all templates.

I'd go with spaces, really as this seems to be more used. In any case, consistency is key here. Do not forget to sign the CLA (see [contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc))

Thanks again!

**Comment by FrontierPsychiatrist** [comment]
Sure, I'll sign them. Which project should I select, initializr is not in the list?

No problem about another fix - a fix is a fix :)

**Comment by snicoll** [comment]
Oops. Oh well, I've asked someone to add this project to the list. Sorry about that.

**Comment by snicoll** [comment]
This  was fixed in cb86153  - Let me know if that's not the case. Thanks!

**Pull request closed without merging**
