### PR TITLE
Update to latest version of Gradle

### PR DESCRIPTION
**Pull request by mikegehard**

### CODE REVIEW

**Comment by snicoll** [comment]
See #110 and #113 - I am not keen to force everyone to go with the latest. But we could reconsider a more "reasonable" upgrade though

**Comment by mikegehard** [comment]
Thanks for the links Stéphane. Next time I'll do a little research first.
:-)

Can you let me know what is considered reasonable and I'll amend the commit?

**Comment by snicoll** [comment]
I just discussed this with @wilkinsona and he recommended to go ahead with 2.7 so I just did that. Thanks for the PR ;)

**Comment by mikegehard** [comment]
Thanks for the heads up. Keep up the great work!

**Pull request closed without merging**
