### PR TITLE
Upgrade to Azure Spring to 2.0.1

### PR DESCRIPTION
**Pull request by sophiaso**
@Matthew-Dong

### CODE REVIEW

**Comment by snicoll** [comment]
@sophiaso I am confused. 2.0.0 isn't released yet, am I right?

**Comment by sophiaso** [comment]
@snicoll It's released, [maven link](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20a%3A%22azure-spring-boot-bom%22), we decided to align with Spring Boot version, i.e., 2.x.x for Spring 2.x.x, so it's 2.0.0. The only concern is the 1.x.x is skipped.

**Comment by snicoll** [comment]
I have a feeling that AAD is broken so I'd like a review of https://github.com/Microsoft/azure-spring-boot/issues/281 first.

**Comment by sophiaso** [comment]
@snicoll @Matthew-Dong A new version `2.0.1` has been released. Thanks.

**Comment by snicoll** [comment]
Thanks for the PR. A version range update was missing and we don't want to have holes in range. I've updated in ed952dd

**Pull request closed without merging**
