### PR TITLE
Add restdocs snippets for documentation and stub generation

### PR DESCRIPTION
**Pull request by dsyer**
The wiki docs have been ported over to use the new snippets,
and a new spring-initializr:stubs jar is generated for consumers
(containing wiremock stubs in a "standard" location).

### CODE REVIEW

**Comment by dsyer** [comment]
I was thinking about maybe adding a sample client app as well, showing the usage of the stubs. Good plan?

**Comment by snicoll** [comment]
I think this is probably going too far. I still need to play around with the PR. I believe there are some restodocs duplication that we want to clean first?

**Comment by dsyer** [comment]
Not sure what to make of "too far". If you mean there is some utility code copied from restdocs, I don't see any reason not to do that (it's just not visible in restdocs, but if and when it is we can always delete stuff here).

**Comment by dsyer** [comment]
Here's a sample client test, just for flavour in case anyone is interested. First using Wiremock:

```java
RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureWireMock(port = 0, stubs="classpath:META-INF/io.spring.initializr/initializr-stubs/1.0.0.BUILD-SNAPSHOT")
public class WireMockApplicationTests {

	@Value("${wiremock.server.port}")
	private int port;

	@Autowired
	private RestTemplateBuilder restTemplateBuilder;

	@Test
	public void contextLoads() throws IOException {
		RestTemplate template = restTemplateBuilder
				.interceptors((request, body, execution) -> {
					request.getHeaders().setAccept(Arrays.asList(
							MediaType.valueOf("application/vnd.initializr.v2+json")));
					return execution.execute(request, body);
				}).build();
		assertThat(template.getForEntity("http://localhost:" + port + "/", String.class)
				.getBody()).contains("dependencies");
	}

}
```

or using the stub runner

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureStubRunner(ids = "io.spring.initializr:initializr-stubs:1.0.0.BUILD-SNAPSHOT", classifier = "")
public class StubRunnerApplicationTests {

	@Autowired
	private StubFinder stubFinder;
	
	@Autowired
	private RestTemplateBuilder restTemplateBuilder;
	
	@Test
	public void contextLoads() throws IOException {
		String url = stubFinder.findStubUrl("io.spring.initializr:initializr-stubs").toString();
		RestTemplate template = restTemplateBuilder
				.interceptors((request, body, execution) -> {
					request.getHeaders().setAccept(Arrays.asList(
							MediaType.valueOf("application/vnd.initializr.v2+json")));
					return execution.execute(request, body);
				}).build();
		assertThat(template.getForEntity(url + "/", String.class)
				.getBody()).contains("dependencies");
	}

}
```

**Comment by dsyer** [comment]
With the latest snapshots in spring-cloud Camden this works too (the mock http server):

```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class MockHttpServerApplicationTests {

	@Autowired
	private RestTemplateBuilder restTemplateBuilder;

	@Test
	public void contextLoads() throws IOException {
		RestTemplate template = restTemplateBuilder
				.interceptors((request, body, execution) -> {
					request.getHeaders().setAccept(Arrays.asList(
							MediaType.valueOf("application/vnd.initializr.v2+json")));
					return execution.execute(request, body);
				}).build();
		WireMockRestServiceServer.with(template).baseUrl("http://start.spring.io")
				.stubs("classpath:META-INF/io.spring.initializr/initializr-stubs/1.0.0.BUILD-SNAPSHOT/mappings/**/*.json")
				.ignoreExpectOrder(true).build();
		assertThat(
				template.getForEntity("http://start.spring.io/", String.class).getBody())
						.contains("dependencies");
	}

}
```

**Comment by snicoll** [comment]
OK so my plan is to add that test in `initializr-docs` and include it in the doc. The sample is small enough to warrant that. I hope to be done by tomorrow.

**Comment by wilkinsona** [comment]
REST Docs 1.2 snapshots should remove the need for the copy 'n' paste as it introduces support for [documenting a subsection of a request or response payload](http://docs.spring.io/spring-restdocs/docs/1.2.x-SNAPSHOT/reference/html5/#documenting-your-api-request-response-payloads-subsections).

**Comment by dsyer** [comment]
@wilkinsona thanks for the link. I'll tidy that up when we get this all working.

**Pull request closed without merging**
